### ISSUE TITLE
jQueryMobile loader gif not fetched when processing css

### ISSUE THREAD

**Issue by dmanto** [jhthorsen/mojolicious-plugin-assetpack#100]
Have following test code to try JQM from CDN, whitout using AssetPack plugin (/woa), and using AssetPack plugin (/wa):

[https://github.com/dmanto/mojo-plugin-assetpack-issue_whith_JQM](https://github.com/dmanto/mojo-plugin-assetpack-issue_whith_JQM)

The only asset that is really used is the css non-minified file from JQM.
Running it with morbo and then accessing to:

`localhost:3000/woa`

will access to a simple welcome page without using any asset, and accessing to:

`localhost:3000/wa`

will access to the same welcome page but using the AssetPack plugin to load then JQM css.

The problem is with the ajax-loader.gif asset, it seems that it is not fetched from the JQM repo.

I tried to add the Fetch pipe to solve this, but I get the following error:

`Can't load application from file "/home/daniel/assets_test/assets_test": Can't call method "name" on an undefined value at /home/daniel/.plenv/versions/5.24.0/lib/perl5/site_perl/5.24.0/Mojolicious/Plugin/AssetPack/Pipe/Fetch.pm line 32`

I guess it has something to do with the fact that it is a GIF image, but I'm not sure about that.

**Comment by jhthorsen** [comment]
I think the bug is ```url(data:....)```. A new release is on its way.

**Comment by jhthorsen** [comment]
Thanks for the bug report! 👍

**Comment by dmanto** [comment]
Jan thanks for the promt response

Still have a problem  when running with hypnotoad and chrome browser (although it doesn't seem to make much sense, I admit...)

Running with morbo everything works fine. I can open JQM css:

1. inspecting in chrome with dev tools, from line 926 on:

  ```
/* Loader */
.ui-icon-loading {
	background: url(../../asset/2edfb2ffe3/ajax-loader.gif);
	background-size: 2.875em 2.875em;
}
```
2. Some but in FF, also from line 926 on:

  ```
/* Loader */
.ui-icon-loading {
	background: url(../../asset/2edfb2ffe3/ajax-loader.gif);
	background-size: 2.875em 2.875em;
}
```
That seems and work ok on both cases. Now with hypnotad:

3. inspecting in chrome (un minimized with {}), from line 975:

  ```
.ui-icon-loading {
    background: url(images/ajax-loader.gif);
    background-size: 2.875em 2.875em
}
``` 
4. now with FF, from line 744:

  ```
.ui-icon-loading {
	background:url(../../asset/2edfb2ffe3/ajax-loader.gif);
	background-size:2.875em 2.875em
}
```

Just to be clear, case 3 is the one not working, as you can see in the url() sentence, it ends up looking for ajax-loader.gif asset in css directory, that is:

`http://localhost:8080/asset/3907fc9b75/images/ajax-loader.gif
`

so it doesn't find it and you get the 404 Not Found from the server

**Comment by jhthorsen** [comment]
I don't really care about the browser in this case. Try to use "curl" or "wget" instead. If they show the correct data, then it's probably just browser cache which is the issue. Try doing a hot reload (CTRL+R, CMD+R) or change the assets so you get a new checksum.

**Comment by jhthorsen** [comment]
Cool! Glad it worked out 😄
