### ISSUE TITLE
Can't locate object method "start_range"

### ISSUE THREAD

**Issue by coolo** [jhthorsen/mojolicious-plugin-assetpack#104]
We run mojo 7.05 and assetpack 1.17 in production

and I've seen two errors like this when looking at the log:
Can't locate object method "start_range" via package "Mojolicious::Plugin::AssetPack::Asset" at 
         /usr/lib/perl5/vendor_perl/5.18.2/Mojolicious/Static.pm

I can't reproduce this, but filing this for completeness

**Comment by jhthorsen** [comment]
I think I can with something like this:

https://github.com/kraih/mojo/blob/master/t/mojolicious/static_lite_app.t#L80

**Comment by jhthorsen** [comment]
Sorry for the late fix! This will soon be available on CPAN.
