### ISSUE TITLE
Following scss includes and downloading them does not respect paths

### ISSUE THREAD

**Issue by marcusramberg** [jhthorsen/mojolicious-plugin-assetpack#107]
if you have an asset foo that includes _bar and foo/baz , and foo/baz includes _bar (locally under foo/) it will not be downloaded automatically.

**Comment by jhthorsen** [comment]
Could you provide an example project where this happens?

**Comment by marcusramberg** [comment]
Including https://raw.githubusercontent.com/select2/select2/master/src/scss/core.scss will cause this issue.

**Comment by jhthorsen** [comment]
Thanks!

**Comment by jhthorsen** [comment]
Now I get it: Pipe::Sass tries to download many different files in order, so it first tries to download "_layout.scss" which it cannot find, but then afterwards it downloads "layout.scss" which does exist. I will see if I can silence the warning somehow, but at least the code works as expected.

if Pipe::Sass fail to download all of the various allowed SASS filenames, it will fail loudly.

https://github.com/jhthorsen/mojolicious-plugin-assetpack/blob/master/lib/Mojolicious/Plugin/AssetPack/Pipe/Sass.pm#L77-L83

**Comment by jhthorsen** [comment]
Another thing to fix is that assetpack.db should prevent Pipe::Sass from even trying to fetch the files later on.

**Comment by jhthorsen** [comment]
This is now fixed.
