### ISSUE TITLE
assetpack.def directory

### ISSUE THREAD

**Issue by dmanto** [jhthorsen/mojolicious-plugin-assetpack#110]
It is not clear in the documentation (to me at least :) ) that assetpack.def should be in "assets" directory. I put it in home directory, and of course it didn't work.

Anyway I think the assets directory is a great place for this file, but probably should be stated clearly in the docs

**Comment by jhthorsen** [comment]
Could you help me out with wording and where this should be stated in the doc?

**Comment by dmanto** [comment]
I would mention it at

https://metacpan.org/pod/distribution/Mojolicious-Plugin-AssetPack/lib/Mojolicious/Plugin/AssetPack/Guides/Tutorial.pod#Defining-assets-in-a-definition-file

Instead of:

```comments
 The definition file can also be defined in the "DATA" section.
```
You could put something like:
```comments
The definition file should be located in the "assets" directory, or optionally defined it in the "DATA" section.
```

**Comment by mrenvoize** [comment]
I just got caught out by this exact same thing... dmanto's alternative wording seems sensible to me

**Comment by jhthorsen** [comment]
Thank you! 👍
