### ISSUE TITLE
Get processed asset by simple url

### ISSUE THREAD

**Issue by mche** [jhthorsen/mojolicious-plugin-assetpack#114]
Hi Jan!

I need to get whole processed asset content by url.
But url must be simler than **http://my-domain.com/asset/18d9939d83/foo.js**
like **http://my-domain.com/assets/foo.js** (skip checksum)

Is there an any documented or known way to solve the problem?

Thanks.

**Comment by mche** [comment]
Oh, now solved by route cb:

```
 $app->routes->route('/assets/*name')->via(qw(HEAD GET))
    ->name('assetpack by name')->to(cb => \&_serve_by_name);
 

sub _serve_by_name {
  my $c        = shift;
  my $helper   = $c->stash('assetpack.helper');
  my $self     = $c->$helper;
  my $topic = $c->stash('name');
 
   if (my $assets = $self->{by_topic}{$topic}) {
    $c->stash('checksum' => $assets->[0]->checksum);
    return &Mojolicious::Plugin::AssetPack::_serve($c);
  }
 
  $c->render(text => "// No such asset '$topic'\n", status => 404);
}
```

**Comment by jhthorsen** [comment]
That is really not the way to fix it. You're way too deep into the internals of AssetPack.

First I need to inform you that doing what you want will cause caching issues for browsers.

Second, here is how you can do it:

```
$app->routes->route('/assets/*name')
  ->via(qw(HEAD GET))
  ->name('assetpack by name')
  ->to(cb => sub {
    my $c      = shift;
    my $topic  = $c->stash('name');
    my $assets = $c->asset->processed($name);

    return $c->render(text => $assets->map('content')->join) if $assets;
    return $c->render(text => "// No such asset '$topic'\n", status => 404);
  });
```

Your application should already know the helper name. `assetpack.helper` is a private variable, which may very well be renamed in the future

You should also never poke around in the hash variables in AssetPack, such as `$self->{by_topic}{$topic}`.

In https://github.com/jhthorsen/mojolicious-plugin-assetpack/blob/master/t/css.t#L51 I use the processed() method to inline the javascript inside the markup.

See also https://metacpan.org/pod/Mojolicious::Plugin::AssetPack#processed

**Comment by mche** [comment]
Ok, thanks.

I wrote pipe combine content of assets to cache file [here](https://github.com/mche/Mojolicious-Plugin-AssetPack-Che/blob/master/lib/Mojolicious/Plugin/AssetPack/Pipe/CombineFile.pm)

```
# in process pipe
# instead of Mojolicious::Plugin::AssetPack::Asset->new(...)->...->content($joined_content)
$assetpack->store->save(\$joined_content, ...);

# and then serve content by topic
my $asset = $assetpack->store->load(...);
$assetpack->store->serve_asset($c, $asset);
```

I would like that asset is Mojo::Asset::File instead of Mojo::Asset::Memory


--
Regards

**Comment by jhthorsen** [comment]
Your pipe also use internals in AssetPack...

Why do you need to change this?
https://github.com/mche/Mojolicious-Plugin-AssetPack-Che/blob/master/lib/Mojolicious/Plugin/AssetPack/Pipe/CombineFile.pm#L9

https://github.com/mche/Mojolicious-Plugin-AssetPack-Che/blob/master/lib/Mojolicious/Plugin/AssetPack/Pipe/CombineFile.pm#L10 should just be:
```
$self->app->routes(...)
```

**Comment by mche** [comment]
>  Why do you need to change this?
https://github.com/mche/Mojolicious-Plugin-AssetPack-Che/blob/master/lib/Mojolicious/Plugin/AssetPack/Pipe/CombineFile.pm#L9

I need combine html files but you remove mapping:

https://github.com/jhthorsen/mojolicious-plugin-assetpack/blob/master/lib/Mojolicious/Plugin/AssetPack/Store.pm#L22

**Comment by mche** [comment]
> https://github.com/mche/Mojolicious-Plugin-AssetPack-Che/blob/master/lib/Mojolicious/Plugin/AssetPack/Pipe/CombineFile.pm#L10 should just be:
> $self->app->routes(...)

`Can't locate object method "app" via package "Mojolicious::Plugin::AssetPack"`

**Comment by jhthorsen** [comment]
I wonder why I delete those type mappings... I'll take a PR for getting them back.

You're combining and serving HTML..? How? Why..?

`Can't locate object method "app" via package "Mojolicious::Plugin::AssetPack"`: You're doing something wrong. The method is there: https://github.com/jhthorsen/mojolicious-plugin-assetpack/blob/master/lib/Mojolicious/Plugin/AssetPack/Pipe.pm#L16 I'm even using it in existing pipes, like here: https://github.com/jhthorsen/mojolicious-plugin-assetpack/blob/master/lib/Mojolicious/Plugin/AssetPack/Pipe/Riotjs.pm#L29

**Comment by mche** [comment]
> Why..?

There is project with javascript framework with so called "_component_" style. Each of components have self js controller and one or more small html templates. Now my AssetPack pipe joins lot of htmls and on client side asset split to  separate templates.

> $self->app->routes(...)

Works, sorry
