### ISSUE TITLE
How to access Javascript source maps?

### ISSUE THREAD

**Issue by AndrewIsh** [jhthorsen/mojolicious-plugin-assetpack#116]
I'm looking for advice for the best way to make Javascript source maps available when adding assets that include them. Here's an example:

assets.def:
```
! libraries.js
< https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.1/angular.min.js
```

Will go and fetch minified angular.js which, since it has an associated .map file, has a line right at the bottom of it
```
//# sourceMappingURL=angular.min.js.map
```
which the browser duly parses (if the user has source maps enabled in their browser) and attempts to retrieve. Unfortunately, this results in the browser attempting to fetch something along the lines of:
```
/asset/78069f9f3a/angular.min.js.map
```
which is, of course, not available, resulting in (in my case) the following warning in the Chrome JS console:
```
Devtools failed to parse SourceMap: https://myserver.com/asset/78069f9f3a/angular.min.js.map
```

I'm wondering how best to address this? I'm wondering if support similar to that provided for CSS fonts is a way forward, in which AssetPack parses font files and retrieves associated font files.

Any thoughts?

**Comment by jhthorsen** [comment]
Hi, thanks for reporting in.

Currently, the only part of AssetPack that support source maps is the Sass pipe. I've been considering adding source map support for Javascript as well, but it will require `npm`.

But I guess your question is a bit different, since the source map already exists. Right now, the way you can hack it is to download the source map and place it in your `public/source-maps` directory and then change sourceMappingURL to something like `../../source-maps/angular.min.js.map`.

I'm leaving this issue open, since adding support for source maps for Javascript automatically is something I want myself as well, but unfortunately there's no perl module that does that.

**Comment by jhthorsen** [comment]
I wonder if we also extend the "Fetch" pipe to automatically download and include source maps, for the javascript that already have a `sourceMappingURL`. 

Here is the Sass commit for source maps: https://github.com/jhthorsen/mojolicious-plugin-assetpack/commit/0b9b42b56656473780f10b8d2574e167b5f85486

**Comment by AndrewIsh** [comment]
That sounds like an excellent idea. I'll be happy to look at this and submit a PR if you like?

**Comment by jhthorsen** [comment]
Yeah, that would be awesome. I might be wrong, but you could try fiddling around with the regexp in the "Fetch" pipe and copy/paste https://github.com/jhthorsen/mojolicious-plugin-assetpack/blob/master/t/fetch-all.t into a `fetch-source-map.t` file and see what happens... Maybe something like this:

```
use lib '.';
use t::Helper;

plan skip_all => 'TEST_ONLINE=1' unless $ENV{TEST_ONLINE} or -e '.test-everything';

my $t = t::Helper->t(pipes => [qw(Javascript Fetch)]);
$t->app->asset->process('app.js' => 'https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.1/angular.min.js');

$t->get_ok('/')->status_is(200);
$t->get_ok($t->tx->res->dom->at('link')->{href})->status_is(200)
  ->content_like(qr{sourceMappingURL=../../\Easset/\w+/angular\.min\.js\.map});

done_testing;

__DATA__
@@ index.html.ep
%= asset 'app.js'
```

**Comment by AndrewIsh** [comment]
Many thanks for the test suggestion.

I've now created [a PR](https://github.com/jhthorsen/mojolicious-plugin-assetpack/pull/117). It parses source map URLs and retrieves the associated source map and makes it available as an asset.

I'm not sure if the approach I have taken is correct, I'll be happy to receive feedback!

**Comment by AndrewIsh** [comment]
I noticed the build is failing, but I'm not sure why. The error in the build report looks like I've got the syntax in my test wrong, but I can't see any difference between it and `fetch-all.t` that I used as a template

**Comment by jhthorsen** [comment]
Thanks for the PR 👍 

I'm closing this issue in favour of the PR #117.
