### ISSUE TITLE
Sass pipe sees @import in comments

### ISSUE THREAD

**Issue by bwilber** [jhthorsen/mojolicious-plugin-assetpack#121]
Hi.  Bootstrap has this comment in _reboot.scss:
```
// Wrap `@viewport` with `@at-root` for when folks do a nested import (e.g.,
// `.class-name { @import "bootstrap"; }`).
```
This creates an infinite loop in Pipe::Sass.

**Comment by jhthorsen** [comment]
Thanks for reporting in.

Unfortunately, I won't have time to look at this until some time in the middle of February.
