### ISSUE TITLE
PrePR: nested topics

### ISSUE THREAD

**Issue by mche** [jhthorsen/mojolicious-plugin-assetpack#122]
Hi Jan!

A little enhancement for nested topics [here](https://github.com/jhthorsen/mojolicious-plugin-assetpack/compare/master...mche:master)

An documentation will come later if you will be satisfied.

**Comment by jhthorsen** [comment]
What does this solve?

**Comment by mche** [comment]
One topic can place to anothers:

```
$app->asset->process(foo=>qw(foo1.js foo2.js));
$app->asset->process(bar=>qw(foo bar1.js bar2.js));
$app->asset->process(baz=>qw(bar baz1.js baz2.js));
```

**Comment by jhthorsen** [comment]
I still don't understand what the usecase is.

**Comment by mche** [comment]
As say on Far East: _if you doesn't then you doesn't_

So none issue 👎
