### ISSUE TITLE
Should I be able to serve `/assets/` directly from `$cache` via nginx rather than via my app

### ISSUE THREAD

**Issue by guest20** [jhthorsen/mojolicious-plugin-assetpack#128]
In my app, I'd like the following work flow:

1. live-generate the assets in dev, so life with -w and automagical assetpacking is amazing
1. ssh to my production box, where hypnotoad is behind nginx (nginx terminates ssl, adds headers, #JustNginxStuff)
1. cd $myapp and git pull, do a hypnotoad upgrade, which generates assets at startup 
1. fill some directory (ideally outside `$app->home`) with `$sum/filename.css` via `$app->asset->process;` + `assetpack.def` 
1. serve those generated contents directly via nginx (without requesting them from the app)

To me serving static files directly from disk is desirable because my crappy vps only has enough ram for 4 workers and I'd like them to be dedicated to generating dynamic web pages. nginx is very good at `sendfile`ing generated css/js, and having it do so leaves more ram for my friend the `hypnotoad`.

Before `AssetPack`ing my files, they just lived in `pubic/` and I served them via some one-off generated nginx rules, but this resulted in 11 or so requests for a page that's pretty much just `Text::MultiMarkdown` + `hilight.js`, which isn't great either.

From my (somewhat shallow) investigations It looks like I'm most of the way just by `AssetPacking` my resources at all, but the sums I see on disk aren't the same as the ones I see in my `<head`, so nginx is going to have a bad time trying to serve them up. I think this means that there's a phase in the pipelining that's not cached in that directory, but I'm not really sure.

Should the "final" form of the asset also be cached on disk?

**Comment by jhthorsen** [comment]
I would set up nginx to cache the assets generated from your mojolicious application. That is by far the simplest solution to your problem. That way, only one request will hit your application and assets will be served from disk later on.

**Comment by guest20** [comment]
That's a fair point, nginx based caching sounds like a good start, though I'd imagine my workers will still grow larger when they receive that first request (since they need to slurp all the things into memory).

Looking through the other open issues, it looks like I want something like the `::AssetPack::Shim` you described in #90. I basically see 3 variants to the behaviour: 

1. @coolo style pre-packaged resources (fill a directory from a `::Command`, stick that in an rpm)
1. generate the resource directory before starting (using the same `::Command` as above)
1. fill the resource directory on app startup.

I think these all would require a simple static `::Plugin::AssetPack` that simply loads the `.db` at startup and produces urls when `%= asset` is called.

Would you be open to such a patch?

**Comment by coolo** [comment]
Just for reference: we use https://github.com/os-autoinst/openQA/blob/master/script/generate-packed-assets

**Comment by jhthorsen** [comment]
I would be open to a "Shim" package, but I'm trying to get rid of the ".db" file. This work is going pretty slow, but that the goal is still there.

The Shim package don't need the .db file though, since it can hold all the information it needs internally.

**Comment by guest20** [comment]
@jhthorsen without the `.db` file, how do I get from the names in `assetpack.def` to the checksummed names used in urls?

**Comment by jhthorsen** [comment]
The checksum comes from the input files, which are always read anyways. Something like this:

sum(join ":”, map { sum $file->content } @input_files);

One of the main reasons for the db file was to track files downloaded, but it’s not required if I can just map the URL directly to the cached file instead.

**Comment by guest20** [comment]
To me it doesn't make a lot of sense to slurp and re-hash my assets on startup when they're already pre-generated / pre-packaged. If the `.db` is the wrong place for it then maybe a `.yaml` file along with the packaged assets would do the job:

```
assets:
  blog.css: 3004e2a997
  blog.js: 3009974e2a
```

That should give the shim enough information to generate urls without having to slurp the content of all the assets.

**Comment by jhthorsen** [comment]
AssetPack always slurp your files. What you're talking about is a new feature. What I'm talking about is to get rid of the db-file, since it's quite annoying when using git and collaborating with others, but keeping the rest of the logic as-is.

**Comment by guest20** [comment]
> What you're talking about is a new feature. 

Yep. An `::AssetPack::Static` shim is indeed a new feature and with a little bit of pre-work this very shim would be able to generate urls without ever having to read/hash any of the resources, which seems like an over-all saving, especially when the resources are served statically from outside the application,

> What I'm talking about is to get rid of the db-file,

Sure. the `.yaml` file I'm describing here would not be versioned by git. It would either live in a separate package/directory (along with the assets), or be generated into a `.gitignore`ed directory on startup. Exactly where the file lives would need to be taken as a config option when the plugin/shim are loaded, and if absent the current slurp-n-hash behaviour can be used.

Maybe it would be easier for me to to explain this in a PR?

**Comment by jhthorsen** [comment]
Any YAML parsing module will not be dependency for this project. There's simply no need for it.

I don't mind a PR at all, but what I believe is that the code in the PR need to generate a `MyApp::Plugin::AssetPack` module (that name need to be configurable) that provides an `asset()` helper that bypass all the pipes and the rest of the `M::P::AssetPack` logic. The idea is that "MyApp" can then be packaged without any of the dependencies that AssetPack require.

MyApp can then have something like this:

```
my $assetpack = !$ENV{MYAPP_USE_ASSETPACK_SHIM} && eval "require Mojolicious::Plugin::AssetPack; 1"; 
$app->plugin($assetpack ? "AssetPack" : "MyApp::Plugin::AssetPack" => $config);
```

**Comment by jhthorsen** [comment]
I think the shim could look something like this:

```
package MyApp::Plugin::AssetPack;

my %BY_TOPIC;

has minify  => 1;            # Probably a static value
has route   => sub {...};    # Same as Mojolicious::Plugin::AssetPack
has store   => undef;        # I do not think this module can have a store
has tag_for => sub {...};    # Not sure how to make this
has ua      => undef;        # This module should not require a user-agent

sub pipe {undef}

sub process {
  my ($self, $topic, @input) = @_;
  $self->route unless $self->{route_added}++;
  return $self;
}

sub processed { $BY_TOPIC{$_[1]} }

sub register {
  my ($self, $app, $config) = @_;
  my $helper = $config->{helper} || 'asset';

  if ($app->renderer->helpers->{$helper}) {
    return $app->log->debug("AssetPack: Helper $helper() is already registered.");
  }

  $app->defaults('assetpack.helper' => $helper);
  $app->helper($helper => sub { @_ == 1 ? $self : $self->_render_tags(@_) });

  $BY_TOPIC = $self->ASSETS;
}

sub _render_tags {
  my ($self, $c, $topic, @attrs) = @_;
  my $route = $self->route;

  my $assets = $BY_TOPIC{$topic} ||= $self->_static_asset($topic);
  my %args = (base_url => $route->pattern->defaults->{base_url} || '', topic => $topic);
  $args{base_url} =~ s!/+$!!;

  return $assets->map($self->tag_for, $c, \%args, @attrs)->join("\n");
}

sub _static_asset {
  my ($self, $topic) = @_;
  my $asset = $self->store->asset($topic) or die qq(No assets registered by topic "$topic".);
  my $assets = Mojo::Collection->new($asset);
  $self->{by_checksum}{$_->checksum} = $_ for @$assets;
  return $assets;
}

sub ASSETS {...}    # Generated code

1;
```

**Comment by jhthorsen** [comment]
I'm going to close this issue, since I don't think it will ever be supported.

You might also want to check out https://metacpan.org/pod/Mojolicious::Plugin::Webpack, since it indeed creates static files on the disk that is easy to package. The plugin also contains code that will automatically convert assetpack.def files into webpack entry files, so it shouldn't be too hard to try it out.

A shim can also be generated by Mojolicious::Plugin::Webpack, making it an completely optional module.
