### ISSUE TITLE
Mojolicious-Plugin-AssetPack-Backcompat is not available

### ISSUE THREAD

**Issue by henrich** [jhthorsen/mojolicious-plugin-assetpack#129]
I got an error with building openQA
> Can't locate Mojolicious/Plugin/AssetPack/Backcompat.pm in @INC (you may need
>        to install the Mojolicious::Plugin::AssetPack::Backcompat module)

and lib/Mojolicious/Plugin/AssetPack.pm: 
>    $app->log->warn(
>      'https://metacpan.org/release/Mojolicious-Plugin-AssetPack-Backcompat is required');

However, it is not available at this URL. Can I avoid this?

**Comment by jhthorsen** [comment]
Oh. I’ve forgotten to update that message.

The backcompat module required time and effort, which I don’t have. The module has been deprecated for quite some time, so I decided it was time to remove it.

It is available on backpan and github though.
