### ISSUE TITLE
package Mojolicious::Plugin::AssetPack::Pipe::RollupJs misspelled

### ISSUE THREAD

**Issue by mario-minati** [jhthorsen/mojolicious-plugin-assetpack#130]
The file ist named Rollup**j**s.pm, the package name is Rollup**J**s. Therefor the pipe cannot be instantiated.

Error:
Can't locate object method "new" via package "Mojolicious::Plugin::AssetPack::Pipe::Rollupjs"

**Comment by jhthorsen** [comment]
Oh! I messed up because the osx filesystem is case-insensitive when it tries to locate files.

Hopefully fixed in 2.00.
