### ISSUE TITLE
Could not find input asset "js/bootbox.js"

### ISSUE THREAD

**Issue by user1313** [jhthorsen/mojolicious-plugin-assetpack#132]
No matter what i tried, relative and absolute path, i always get this:

root@west:/home/user# morbo project0/main
Server available at http://127.0.0.1:3000
Can't load application from file "/media/array/home/user/project0/main": Could not find input asset "/media/array/home/user/project0/js/bootbox.js". at /usr/local/share/perl/5.24.1/Mojolicious/Plugin/AssetPack.pm line 70, <DATA> line 192.
Compilation failed in require at (eval 89) line 1, <DATA> line 192.

The relevant code:

plugin 'AssetPack' => { pipes => [qw(Less Sass Css CoffeeScript Riotjs JavaScript Combine)] };

app->asset->process(
    "javascripts" => ( "/media/array/home/user/project0/js/bootbox.js" )
    );

Installed the plugin with
"curl -L https://cpanmin.us | perl - -M https://cpan.metacpan.org -n Mojolicious::Plugin::AssetPack"

Perl: | v5.24.1 (linux)
Mojolicious: | 7.60 (Doughnut)

Thanks for any help.

**Comment by jhthorsen** [comment]
It needs to be relative to one of the paths in `@{app->asset->store->paths}`.

Have you looked at https://metacpan.org/pod/distribution/Mojolicious-Plugin-AssetPack/lib/Mojolicious/Plugin/AssetPack/Guides/Tutorial.pod ?

**Comment by user1313** [comment]
Works. No, i checked docs at http://search.cpan.org/~jhthorsen/Mojolicious-Plugin-AssetPack-2.02/lib/Mojolicious/Plugin/AssetPack.pm
only. Appreciated!
