### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by gmorten1** [jhthorsen/mojolicious-plugin-assetpack#140]
the Qualys web application scanner reported XSS vulnerabilities on the "No such asset" message for bogus asset paths. i've verified. here's an example:

` /asset/93afbc465c/sitemap.xml<script>alert('ouch')</script>`

(try this in any mojo app, doesn't need a valid asset)

**Comment by jhthorsen** [comment]
How can you reproduce this?

**Comment by gmorten1** [comment]
hi jan,

by default, the path to any bad asset name is passed through unescaped in the error message in AssetPack.pm line 216

an attacker can construct a link to a non-existent asset in your application and cause arbitrary javascript to execute in context of your user's browser 

to reproduce:
1. use the simplest AssetPack example code from your github synopsis (no custom 404 handling, no asset fallback)
2. start you application on localhost port 3000
3. open this url `http://localhost:3000/asset/93afbc465c/sitemap.xml%3Cscript%3Ealert('ouch')%3C/script%3E` in chrome or firefox, it will fire the javascript alert embedded in the bad asset name

someone told me it doesn't fire the js in safari, but i didn't investigate. maybe they don't allow js in a 404?

**Comment by jhthorsen** [comment]
Thanks for the details. This is now fixed in 2.09.
