### ISSUE TITLE
Using existing asset for...

### ISSUE THREAD

**Issue by romkaspb** [jhthorsen/mojolicious-plugin-assetpack#37]
Hi there!

I'm using morbo, and its hard to using your great plugin. Because on every static request I see in logs smth like this:

[Thu Feb 12 17:13:15 2015] [debug] Using existing asset for common.js: ../../httpdocs/packed/common-027d6e3daae39a0de730902ad4cc6dfc.js
[Thu Feb 12 17:13:15 2015] [debug] Using existing asset for subscribe.js: ../../httpdocs/packed/subscribe-203e88ee3a8d810a3df56c1b4bb9852e.js
[Thu Feb 12 17:13:15 2015] [debug] Using existing asset for callback.js: ../../httpdocs/packed/callback-d1307470417fb69e1998fb19bcbda693.js

And I can't see what really happens in rendering. 
I solved it by replacing 311 line in AssetPack.pm to this:
``` perl
$self->{log}->debug("Using existing asset for $moniker: @{[$file->path]}") if $ENV{MOJO_ASSETPACK_DEBUG};
```
But it's a very bad solution, you know :)

Please, do something to solve that problem.

Great thanks!

Sorry for my English :)

**Comment by jhthorsen** [comment]
Thanks for the feedback!

I'm not going to make a new release just yet, but the next version will have less logging. You can get it manually using ```cpanm```:

    cpanm https://github.com/jhthorsen/mojolicious-plugin-assetpack/archive/master.tar.gz
