### ISSUE TITLE
Fallback in production mode leads to confusing errors

### ISSUE THREAD

**Issue by zoffixznet** [jhthorsen/mojolicious-plugin-assetpack#44]
Steps to reproduce:
```
git clone https://github.com/zoffixznet/SAMPLES-Mojo-Asset-Pack-Errors;
cd SAMPLES-Mojo-Asset-Pack-Errors/;
morbo -w . test.pl;
```
Open the brower at [http://127.0.0.1:3000/](http://127.0.0.1:3000/) and see there are no error assets, as expected.

Open the two files `public/one.scss` and `public/two.scss`. Uncomment `color: $one-color;` line in `public/one.scss` and refresh the page. We get the correct error now, `Error: Undefined variable: '$one-color'."```.

Comment the `color: $one-color;` back to the way it was and uncomment `color: $two-color;` in `public/two.scss`. Refresh the page. We have an incorrect message now. It still says `$one-color` is not defined, even though now it should say `$two-color` is undefined.

I played around with the code, and this seems to happen because when there are errors in the first file given to `->asset`, the plugin still generates `.css` or `.min.css` file instead of generating `.err.` version.

To note: if we don't generate an error in `$one-color` first and go straight to `$two-color`, then no errors will be displayed on the page. I think that's how it's supposed to work due to fallback, but then this behaviour is inconsistent with when errors are in the first file (`one.scss`)

**Comment by jhthorsen** [comment]
Thanks. I'll look into it.

**Comment by jhthorsen** [comment]
I will remove fallback mode. I've been trying to rewrite the internals, and fallback mode just doesn't feel right.

**Comment by zoffixznet** [comment]
+1
I don't see a good reason to have it.

**Comment by jhthorsen** [comment]
Could you try out master to see if it behaves more predictive?
```
cpanm https://github.com/jhthorsen/mojolicious-plugin-assetpack/archive/master.tar.gz
```

**Comment by zoffixznet** [comment]
Yeah, works fine. Tells me the correct errors when they're there.

**Comment by jhthorsen** [comment]
Sweet! I'll make a new release tomorrow.
