### ISSUE TITLE
warning about memory stored assets appearing in wrong place

### ISSUE THREAD

**Issue by coolo** [jhthorsen/mojolicious-plugin-assetpack#56]
The warning appears if it can't find a writable out_dir, but this might be perfectly fine (in case of predefined assets and the app running as nobody) - the warning should either be removed or only appear in case assets need to be genenerated without out_dir.

**Comment by jhthorsen** [comment]
:+1: I totally agree. Will fix it as soon as possible.

**Comment by jhthorsen** [comment]
Sorry for the delay. I've been absent.
