### ISSUE TITLE
Incorrect Handling of Relative Paths in CSS Files

### ISSUE THREAD

**Issue by zoffixznet** [jhthorsen/mojolicious-plugin-assetpack#63]
First, don't know if this _should_ be fixed, as properly fixing it would likely require parsing all CSS files, which might add some overhead, which is annoying when developing. I don't mind fixing it, if we agree on whether it should be fixed and how it should be fixed.

I stumbed on this issue when trying to add [bluimp gallery](https://github.com/blueimp/Gallery) that uses relative URLs for the image assets in its CSS files.

There's #24, for which the solution is this: https://github.com/jhthorsen/mojolicious-plugin-assetpack/blob/94b14d5154915f25e0c7b99295078d03b0a61756/t/expand-src-url-example.t#L10

Would that be a recommended solution for this case as well or do we fix the issue?

### Use case
Adding third-party widgets and things that use relative URLs in their CSS

### Issue
Currently, AssetPack does not fix relative URLs in CSS files. So if the included CSS file is not in `public/foo`, when it's placed in `public/packed`, the relative URLs inside of it will be wrong.

### Steps to reproduce
Get the test case app:
```bash
git clone https://github.com/zoffixznet/debug/;
cd debug;
git checkout d86c6c2ed313d43d9949714c42827af9a744fb7c;
morbo app.pl;
```
#### Expected results
You can see an image of Homer in the background

#### Current results
The page is blank

**Comment by jhthorsen** [comment]
I don't see any way to fix this automatically. How can you tell where the referred asset is located?

**Comment by zoffixznet** [comment]
Ah, right. I totally forgot about needing `sass` and other things. Then yes, this would be useful :)

**Comment by jhthorsen** [comment]
How about making an extension that makes https://github.com/jhthorsen/mojolicious-plugin-assetpack/blob/94b14d5154915f25e0c7b99295078d03b0a61756/t/expand-src-url-example.t easier to do? Extension = some some common preprocessor that can be chained with any other preprocessor and search/replace for "stuff" ?

    package Mojolicious::Plugin::AssetPack::Preprocessor::Rewrite;
    has replace => sub { die "required" };
    has with => sub { die "required" };
    sub process {
      my ($self, $assetpack, $text, $path) = @_;
      my ($replace, $with) = ($self->replace, $self->with);
      $$text = s!$replace!$with!g;
    }
    ......
    $app->asset->preprocessors->add(css => Rewrite => {replace => qr{fff}, with => "000"});

"with" is probably not the best attribute name and it should probably even support a callback. But anyway... What do you think?

**Comment by zoffixznet** [comment]
After a conversation on IRC, we decided this way is the easiest way to deal with the issue by the user: https://github.com/jhthorsen/mojolicious-plugin-assetpack/blob/94b14d5154915f25e0c7b99295078d03b0a61756/t/expand-src-url-example.t
