### ISSUE TITLE
Warnings: Use of uninitialized value in split at Mojolicious/Plugin/AssetPack/Preprocessor/Scss.pm line 203.

### ISSUE THREAD

**Issue by zoffixznet** [jhthorsen/mojolicious-plugin-assetpack#65]
Getting those warnings in output.

From what I can see, this has the potential for the SASS_PATH to become undefined: https://github.com/jhthorsen/mojolicious-plugin-assetpack/blob/master/lib/Mojolicious/Plugin/AssetPack/Preprocessor/Scss.pm#L173

**Comment by jhthorsen** [comment]
Oh! I've experienced this myself, but thought join() would result in empty string and not under if the list was empty.

**Comment by zoffixznet** [comment]
Oh, sorry, it does result in an empty string. Then I've no idea how the warning originates. I noticed them when trying to run the test suite on Corvos: https://metacpan.org/pod/Convos

**Comment by zoffixznet** [comment]
This seems stale and no solid test case exists for reproducing the issue. Closing.

**Comment by jhthorsen** [comment]
I can't come up with any other reason why this might happen than some other module mess up the environment in runtime.
