### ISSUE TITLE
Add option to enable concatenation

### ISSUE THREAD

**Issue by AndrewIsh** [jhthorsen/mojolicious-plugin-assetpack#66]
You may consider this to be beyond the scope of AssetPack but I think it would be hugely useful to add a concatenation step in the packing process. I've an Angular JS app with many dozens of files and while AssetPack does a great job of ensuring they all get loaded and minified, they're still many dozens of files which require many dozens of requests. Enabling AssetPack to concatenate would remove the need for me to have a separate Gulp stage in my workflow.

Any thoughts?

**Comment by zoffixznet** [comment]
Hi,

All those multiple assets actually already get merged into a single one ***when running in production mode**

See [The Modes Manual](https://metacpan.org/pod/distribution/Mojolicious-Plugin-AssetPack/lib/Mojolicious/Plugin/AssetPack/Manual/Modes.pod).

If I'm misunderstanding what you mean or you don't get a single file in production mode, please reopen the Issue.

Thanks.

**Comment by AndrewIsh** [comment]
Nope, my mistake, apologies!
