### ISSUE TITLE
Access to asset checksum

### ISSUE THREAD

**Issue by mrenvoize** [jhthorsen/mojolicious-plugin-assetpack#67]
It would be great to have a shortcut to access an assets checksum (as appended to the resultant filenames).

I am currently doing some regex foo to grab the resultant checksum so I may add it into a X-Assets-Version header in my api responses to allow for an enforced reload of assets triggered via the api response headers.

**Comment by zoffixznet** [comment]
My vote is :-1: on this, because it's adding a new feature that I don't believe is widly needed and can be easily replicated with a single line of code. Here's an example of its use in the template: ```Asset hash is: <%= (asset("app.css") =~ /-(\w{32})\./)[0] %>```

Just an FYI: the lead author for this module is currently on vacation, so it might take a while for them to get back and have a look at this Issue.

**Comment by jhthorsen** [comment]
Yeah. Not sure if I want to add this functionality. Could you explain more how the flow is in your application? I think I would solve it without a header. Maybe simply by comparing the generated assets, since I think a reload should be triggered no matter what the checksum/file name is.

**Comment by mrenvoize** [comment]
The use case is in spa's where the main html page is rarely reloaded after the initial app load.  It's a common case to have version headers in the api responses which the spa's javascript checks against it's own version string with every request and upon a change a full page refresh is triggered, thus enabling the new javascript assets to get pulled from the server.

I was simply using the assets checksum as my version string as it should change only when the assets are changing.

I'm happy to stick with what I've got, a regex similar to the above but inside a swagger around action, but thought it may be something of interest to this project as a whole.

**Comment by jhthorsen** [comment]
This should be possible in #71.
