### ISSUE TITLE
Allow use of scheme relative URLs in online assets

### ISSUE THREAD

**Issue by AndrewIsh** [jhthorsen/mojolicious-plugin-assetpack#69]
Including the following URL as as asset:
```
'//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css'
```

Results in the following error:
"AssetPack could not read //maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css: Asset //maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css could not be fetched"

It would be useful to be able to have scheme relative online assets. Is this in any way possible?

**Comment by jhthorsen** [comment]
Why is that nice? The client never sees these URLs. The scheme is only used by your mojo app to understand how to fetch the asset. I don't see the benefit wher AssetPack first tries https and then falls back to http.

**Comment by AndrewIsh** [comment]
Ah, OK, I'd not appreciated that AssetPack first tries https then falls back to http, I must read the docs more closely in future! That makes sense then. Apologies for the nonsense issue :)

**Comment by jhthorsen** [comment]
@AndrewIsh: No problem! Please send me a pull request with improved documentation. I'm not very surprised this question has come up - and it will probably not be the last.
