### ISSUE TITLE
Duplicated code of loading File::Which module

### ISSUE THREAD

**Issue by keedi** [jhthorsen/mojolicious-plugin-assetpack#74]
There is a duplicated code in `M::P::A::Preprocessor::Scss`.

https://github.com/jhthorsen/mojolicious-plugin-assetpack/blob/1.00/lib/Mojolicious/Plugin/AssetPack/Preprocessor/Scss.pm#L81

**Comment by zoffixznet** [comment]
Thanks for spotting that! Fixed.

**Comment by jhthorsen** [comment]
Thanks!

Note that the preprocessors will be removed. Not entirely sure when, but I imagine before 2017.
