### ISSUE TITLE
Is there a best way to locate other resource like font file?

### ISSUE THREAD

**Issue by keedi** [jhthorsen/mojolicious-plugin-assetpack#75]
Hi.
This is not a issue but a question.

I'm trying to use brand new AssetPack plugin. And I have a question about locating other resources. If I use FontAwesome, then I refered [cookbook document](https://metacpan.org/pod/distribution/Mojolicious-Plugin-AssetPack/lib/Mojolicious/Plugin/AssetPack/Guides/Cookbook.pod#Font-awesome), and made def file like this:

```plain
! app.css
< https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css
< style.scss
```

AssetPack downloads and combine FontAwesome css well. But FontAwesome requires web fonts:

```plain
[Tue Apr  5 19:22:45 2016] [debug] GET "/asset/fonts/fontawesome-webfont.woff2"
...
[Tue Apr  5 19:22:45 2016] [debug] 404 Not Found (0.008048s, 124.254/s)
...
[Tue Apr  5 19:22:45 2016] [debug] GET "/asset/fonts/fontawesome-webfont.ttf"
...
[Tue Apr  5 19:22:45 2016] [debug] 404 Not Found (0.008288s, 120.656/s)
```

I downloaded FontAwesome distribution then unarchived it to somewhere. Then I made `$MOJO_HOME/public/asset/` directory, and linked original web font files using symbolic link under `$MOJO_HOME/public/asset/fonts/`. Is it the right way to use FontAwesome (or Materialize, etc) with AssetPack plugin? Or is there a best way to locate the static files which are not dealed via AssetPack?

Any help will be appreciated. :-)

P.S.
It would be great if how to locate other resources for FontAwesome and Materialize CSS is added to the cookbook document.

**Comment by zoffixznet** [comment]
The Issues are really for... issues. Questions are best asked on the [Mojolicious mailing list](https://groups.google.com/forum/#!forum/mojolicious) or on irc://irc.perl.org/#mojo IRC channel.

Yes, the way to have the assets available is to just have them in the `/public/` somewhere, same as if it were just a regular static page served by a server. There's one caveat: some CSS libraries reference their assets with relative paths, like `../images/foo.gif`, but when AssetPack packs those into a single file, it'll be served from `/` path, which will make those relative paths not function properly. It's beyond the AssetPack's capabilities to fix those paths, so you'd have to fix them manually or not use those libraries via AssetPack.

Lastly, both `FontAwesome` and `Materialize CSS` are available as Mojolicious Plugins as [Mojolicious::Plugin::FontAwesome4](https://metacpan.org/pod/Mojolicious::Plugin::FontAwesome4) and [Mojolicious::Plugin::Materialize](https://metacpan.org/pod/Mojolicious::Plugin::Materialize). These basically use AssetPack to bring in the assets so you don't have to.

Cheers.

**Comment by keedi** [comment]
Thanks for response and sorry for bothering issue list. Next time I'll use the mailing list. :)

**Comment by jhthorsen** [comment]
I'm re-opening this issue because I would very much like to be able to specify font assets in the def file. I'm not entirely sure I want to automatically extract the fonts from the css file, but I think something like this makes sense

```
! app.css
< https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css
< style.scss
```

@keedi: Any other input regarding the new version is greatly appreciated. Here is also a blog post about why I decided to do the rewrite: http://thorsen.pm/perl/2016/02/21/rewriting-assetpack-plugin.html

**Comment by jhthorsen** [comment]
Working on https://github.com/jhthorsen/mojolicious-plugin-assetpack/pull/79 now. t/sass-current-app.t is failing. Will merge it when all tests pass.

**Comment by jhthorsen** [comment]
Please try out f86d189 and let me know if it works out for you.

**Comment by keedi** [comment]
Thanks for "Fetch" feature!

I've tried 1.06 version and it works pretty well.
This is really convenient than below 1.04 version.

P.S.
Just out of curiosity, "Fetch" downloads remote css only, do you have a plan for local resource fetch?

**Comment by jhthorsen** [comment]
Oh. I missed out that part... I don't have a plan for it, since it's a feature I personally don't use. A PR or a new issus is more than welcome, but I don't have an ETA for when it can be implemented.
