### ISSUE TITLE
Maybe AssetPack should not add its /asset route in the end

### ISSUE THREAD

**Issue by HEM42** [jhthorsen/mojolicious-plugin-assetpack#77]
Today with 1.x AssetPack adds it /asset route to the end of all the existing routes.

Maybe this should be added at the time when you initiate asset->process()

Seems you can force it to add its route by issuing  asset->route() right after your asset->process()

**Comment by jhthorsen** [comment]
I totally agree! I'm surprised this even works now.

Thank you 👍
