### ISSUE TITLE
whitespace is (suprisingly) relevant in assetpack.def

### ISSUE THREAD

**Issue by coolo** [jhthorsen/mojolicious-plugin-assetpack#93]
I had a line
```
! codemirror.js<WHITESPACE>
```

Which caused an 'no asset registered to topic 'codemirror.js'. I didn't really expect to make white space a difference.

**Comment by jhthorsen** [comment]
Which whitespace? Can you add quotes or something around the line?

**Comment by coolo** [comment]
Sorry, I fixed my markdown

**Comment by jhthorsen** [comment]
Thanks!
