### ISSUE TITLE
$Pipe::Fetch::URL_RE doesn't support Google Fonts

### ISSUE THREAD

**Issue by yunikim** [jhthorsen/mojolicious-plugin-assetpack#99]
https://github.com/jhthorsen/mojolicious-plugin-assetpack/blob/1.13/lib/Mojolicious/Plugin/AssetPack/Pipe/Fetch.pm#L7

$Pipe::Fetch::URL_RE doesn't match to font url from https://developers.google.com/fonts/ 
because it has no `'` or `"`

i.e. https://fonts.googleapis.com/css?family=Tangerine
```
/* latin */
@font-face {
  font-family: 'Tangerine';
  font-style: normal;
  font-weight: 400;
  src: local('Tangerine'), url(https://fonts.gstatic.com/s/tangerine/v7/HGfsyCL5WASpHOFnouG-RJBw1xU1rKptJj_0jans920.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215, U+E0FF, U+EFFD, U+F000;
}
```

**Comment by yunikim** [comment]
If I add following line before asset->process, Pipe::Fetch fetches font files.

```perl
$Mojolicious::Plugin::AssetPack::Pipe::Fetch::URL_RE = qr{url\((['"]{0,1})(http?.*?)\1\)};
```

**Comment by yunikim** [comment]
closing this issue because https://github.com/jhthorsen/mojolicious-plugin-assetpack/issues/91 describes the same issue.

**Comment by jhthorsen** [comment]
Thanks! A new release will soon be available on CPAN.
